// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyV6bJAm3njU4KasLwxcQaUVRhYpVoOKE',
    appId: '1:733133380454:web:3fbd3906f2be5587d846a7',
    messagingSenderId: '733133380454',
    projectId: 'contravention-routiere',
    authDomain: 'contravention-routiere.firebaseapp.com',
    storageBucket: 'contravention-routiere.appspot.com',
    measurementId: 'G-29JWRZJ7HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm7KP28PkUeRGAIH31IlYuTdWJlNvwk1E',
    appId: '1:733133380454:android:fa80a041b04be28cd846a7',
    messagingSenderId: '733133380454',
    projectId: 'contravention-routiere',
    storageBucket: 'contravention-routiere.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHJcO_bv347Jl4yg8-fbfkLTmwhc3BYO8',
    appId: '1:733133380454:ios:6605ba7f68b6937bd846a7',
    messagingSenderId: '733133380454',
    projectId: 'contravention-routiere',
    storageBucket: 'contravention-routiere.appspot.com',
    iosBundleId: 'com.example.appContravention',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHJcO_bv347Jl4yg8-fbfkLTmwhc3BYO8',
    appId: '1:733133380454:ios:6605ba7f68b6937bd846a7',
    messagingSenderId: '733133380454',
    projectId: 'contravention-routiere',
    storageBucket: 'contravention-routiere.appspot.com',
    iosBundleId: 'com.example.appContravention',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyV6bJAm3njU4KasLwxcQaUVRhYpVoOKE',
    appId: '1:733133380454:web:7a939af80481902ed846a7',
    messagingSenderId: '733133380454',
    projectId: 'contravention-routiere',
    authDomain: 'contravention-routiere.firebaseapp.com',
    storageBucket: 'contravention-routiere.appspot.com',
    measurementId: 'G-LZMESNNFHG',
  );
}
